# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations
2Auth:
  # Cannot be null.
  backend-domain: localhost
  # If empty, no port number is used.
  backend-port: 8081
  # To configure CORS policy. If empty, the default is "*".
  allowedOrigins: "*"
  # To configure the only allowed http methods. If empty, the default are GET, POST, PUT, DELETE.
  allowedHttpMethods: GET, POST, PUT, DELETE
  # This name is combined with the secure cookie prefix "__Host-". If empty, the default is "XYZ_S".
  customSessionIdName: "XYZ_S"

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: false

spring:
  mvc:
    favicon:
      enabled: false
  web:
    resources:
      add-mappings: false
  application:
    name: 2auth-api-gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - JwtTokenRelay
            - ChangeSessionId
            - LogoutIfUnauthorized
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: INFO
        web: INFO