# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations
2Auth:
  # Can be one between <NONE, EMAIL_FOR_FRONTEND, EMAIL_FOR_API, TEST_FOR_FRONTEND, TEST_FOR_API>.
  # Default is TEST_FOR_API.
  registration-confirmation: TEST_FOR_API
  jwt:
    # Time before the JWT expires (in milliseconds). Default is 8 hours.
    time-validity-in-millis: 28800000
    # Time before renewing the key used to sign JWTs (in milliseconds). Default is 24 hours.
    key-time-validity-in-millis: 86400000

spring:
  ssl:
    bundle:
      jks:
        mongo:
          truststore:
            location: ${SSL_MONGO_TRUST_STORE}
            password: ${SSL_MONGO_TRUST_STORE_PASSWORD}
  jackson:
    time-zone: 'Europe/Rome'
    date-format: 'dd-MM-yyyy HH:mm:ss'
  mvc:
    format:
      date: 'dd-MM-yyyy'
      date-time: 'dd-MM-yyyy HH:mm:ss'
    favicon:
      enabled: false
  web:
    resources:
      add-mappings: false
  application:
    name: 2auth-backend
  data:
    mongodb:
      database: 2Auth
      port: 27017
      host: localhost
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: ${DB_AUTH_DB}
      ssl:
        enabled: true
        bundle: mongo
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  error:
    path: "/error_Lg-aieD1zPiG1_L2D6Wwe_avS2I-Avjrq5I8-"
    whitelabel:
      enabled: false
    include-path: never
  ssl:
    enabled: true
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}
    protocol: TLS
    enabled-protocols: TLSv1.3

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: INFO
        web: INFO